Dev
wintermeyer/vutuv pull request #158
Opened 2016-09-16 23:52 UTC by cjfreeze

This PR contains the first implementation of the search_terms feature, as well as minor fixes and optimizations.

2016-09-17 06:24 UTC, wintermeyer commented
`Dev` is not a good name for a pull request. It should have a little bit more information so that I get an idea what it is about.

![bildschirmfoto 2016-09-17 um 08 22 40](https://cloud.githubusercontent.com/assets/69770/18606427/f75d80fc-7caf-11e6-9bd3-8bfc9ed25435.png)

2016-09-17 06:30 UTC, wintermeyer commented
The results of a search should be sorted by not only `similarity` but also by `last_name` + `first_name`.

2016-09-17 06:32 UTC, wintermeyer requested changes
`score` might be a better field name name `similarity`. My bad.

2016-09-17 06:33 UTC, wintermeyer requested changes
The results of a search should be sorted by not only `similarity` but also by `last_name` + `first_name`.

2016-09-17 06:43 UTC, wintermeyer commented on lib/vutuv/registration.ex
> +  alias Vutuv.Repo
Wrong formatting. In case you are mixing tabs and spaces: Don't!
**Only use spaces!**

2016-09-17 06:44 UTC, wintermeyer commented on lib/vutuv/registration.ex
> +      user["emails"]["0"]["value"],
In case a user has more than one e-mail address the other e-mail addresses should be added too.

2016-09-17 06:48 UTC, wintermeyer commented on web/controllers/search_query_controller.ex
> +    |>Enum.sort(&(&1.similarity> &2.similarity)) #sorts by similarity
Should sort by `last_name` and `first_name` in addition to the `similarity`.

2016-09-17 06:51 UTC, wintermeyer requested changes
I like the comments. I only have a couple of small fixes.

2016-09-17 07:03 UTC, wintermeyer requested changes
search_terms are not downcased.

```
mysql> select value from search_terms;
+-------------------------------+
| value                         |
+-------------------------------+
| Stefan                        |
| Wintermeyer                   |
| stefan.wintermeyer@amooma.de  |
| Stefan Wintermeyer            |
| Wintermeyer Stefan            |
| Stefan, Wintermeyer           |
```

They should be downcased. And the search should downcase the search requests.

2016-09-17 07:28 UTC, wintermeyer commented
José Valim should have a `search_terms` with and without the "é".

- José Valim
- Jose Valim

2016-09-17 21:49 UTC, cjfreeze commented on lib/vutuv/registration.ex
> +  alias Vutuv.Repo
I think this one can be blamed on my text editor. I recently upgraded to sublime text 3, and it seems to have trouble remembering my indentation settings for multiple files. I've been looking into it.

2016-09-17 22:01 UTC, cjfreeze commented on web/controllers/search_query_controller.ex
> +    |>Enum.sort(&(&1.similarity> &2.similarity)) #sorts by similarity
So entries with equal `scores` will be alphabetized by last name?

2016-09-18 10:37 UTC, wintermeyer commented on web/controllers/search_query_controller.ex
> +    |>Enum.sort(&(&1.similarity> &2.similarity)) #sorts by similarity
Yes, they should be alphabetized by `last_name` plus `first_name`.

2016-09-18 10:45 UTC, wintermeyer commented on web/router.ex
> +      resources "/search_terms", SearchTermController
Shouldn't this be followed by a `only: [:new, :create, :show, :delete, :index]`?

2016-09-18 10:49 UTC, wintermeyer requested changes
The `search_queries` resource doesn't feel RESTful yet. After a `search_queries#new` it should lead to an `search_queries#show` (with the `id` or the `slug`). Now it leads to `search_queries#index` which doesn't make sense in the RESTful world. One can argue that a search results in a score of 100 and a single entry than we could do a redirect to that user. But that's a second step. Right now I'd like `search_queries` behave like a proper RESTful resource.

2016-09-18 10:54 UTC, wintermeyer commented
`search_queries#index` should only display the `search_queries` of the current user. If no user is logged in it should redirect to `search_queries#new`.

2016-09-19 14:37 UTC, merged