schema user, email_address, authentication, session
wintermeyer/vutuv pull request #575
Opened 2019-03-02 15:53 UTC by hendri-tobing

Schema for user, email_address, authentication, session. Using phauth, arc, and other dependencies.

2019-03-02 16:15 UTC, wintermeyer commented on lib/vutuv_web/uploaders/avatar.ex
> +    sym_link_path = "/var/www/vutuv/avatars/#{nginx_path}/#{timestamp}"
Please define a variable for `/var/www/vutuv/` which can changed in `config/[prod|dev].exs`

Just one place to update this kind of information when needed.

2019-03-02 16:16 UTC, wintermeyer commented on lib/vutuv/Schema/user.ex
> +      |> cast(attrs, [:first_name, :last_name, :middlename, :nickname, :honorific_prefix, :honorific_suffix, :gender, :birthday_day, :birthday_month, :birthday_year, :locale, :verified, :avatar, :act
`:active_slug, :noindex?, :validated?` shouldn't be in this cast or should they? We don't want a user to inject those values in the WebGUI.

2019-03-02 16:18 UTC, wintermeyer commented on lib/vutuv/Schema/user.ex
> +        # All the 3 fields are nil.
Shouldn't this comment say "All 2 fields are nil"?

2019-03-02 16:27 UTC, wintermeyer commented on lib/vutuv/Schema/user.ex
> +        message = "First name or last name must be present"
We have to have a I18n solution for these messages. We can develop the application with the english texts but have to have an easy option to add translations (German being the first).

2019-03-02 16:29 UTC, wintermeyer requested changes
Just some small things. I added comments.

2019-03-06 10:29 UTC, riverrun commented on lib/vutuv/Schema/user.ex
> +        message = "First name or last name must be present"
The translations will be handled in the view layer. We just need to make that the message is correctly added to the changeset, as it is here, and that we update the pot (gettext) files with each message.

2019-03-10 11:02 UTC, hendri-tobing commented
Close this PR #575 override by #580

2019-03-10 11:02 UTC, closed without merging