some updates
wintermeyer/vutuv pull request #580
Opened 2019-03-07 12:23 UTC by hendri-tobing

Sorry, I create a new PR from a fork in my repository for some reasons.

This is, some update of issue #573  and #570. Sorry for the late update, because I lost my work on local for couple days.

2019-03-10 04:05 UTC, riverrun commented
Does this PR override #575? If it does, could you close #575? So that it does not get merged by mistake.

2019-03-10 11:02 UTC, hendri-tobing commented
> Does this PR override #575? If it does, could you close #575? So that it does not get merged by mistake.

Done, thank you.

2019-03-10 11:30 UTC, wintermeyer commented
@hendri-tobing I added @riverrun and I as a reviewer but actually don't know if you are finished with this PR. Is it ready for review?

2019-03-10 12:04 UTC, riverrun requested changes
I have just left a few comments - together with a couple of questions.

2019-03-10 12:04 UTC, riverrun commented on config/test.exs
> +#config :bcrypt_elixir, log_rounds: 4
Let's delete the commented lines - we don't need them.

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv/accounts/roles.ex
> +defmodule Vutuv.Accounts.Role do
Let's change the name of the file to `role.ex` - not `roles.ex`

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv/biographies/profile.ex
> +  def gender_gettext("male") do
Why are we calling gettext from here?

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv/accounts.ex
> +  def get_email_address!(id), do: Repo.get!(EmailAddress, id)
The phoenix generators create bang functions for the 'get_item' function. I think the regular versions (non-bang) are more useful, but what do you think?

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv/accounts/email_address.ex
> +    |> validate_length(:value, max: 80)
Do we want to limit emails to 80 chars? My understanding is that emails can be anything up to 255 chars long.

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv/accounts/user.ex
> +    has_one :profiles, Profile, foreign_key: :user_id, on_delete: :delete_all
With `has_one`, let's use `:profile`, not `:profiles`, and I don't think we need the `foreign_key` entry - it will be user_id by default.

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv/accounts/user.ex
> +    |> unique_email
We won't need the `unique_email` calls in this module if we are checking the emails in the email_addresses table, and ideally we will only be checking for uniqueness in one place.

We could replace this line with `|> cast_assoc(:email_addresses)`

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv_web/controllers/user_controller.ex
> +        profile = Ecto.build_assoc(user, :profiles, %{gender: user_params["gender"], first_name: user_params["first_name"], last_name: user_params["last_name"]})
All this logic (including nearly all Ecto and Repo calls) should be in the relevant context module.

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv_web/controllers/user_controller.ex
> +      Repo.get!(Profile, id)
Again, we should not need to call Repo directly from the controllers

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv_web/controllers/user_controller.ex
> +    post = if id == to_string(user.id) do
The id check is being done three times in this function. We should only need to do it once.

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv_web/router.ex.bak
> +defmodule VutuvWeb.Router do
We can remove all of the `.bak` files - they are just backups created by the Phauxth installer.

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv_web/views/user_view.ex
> +  alias VutuvWeb.UserView
We don't need these Json routes, do we?

2019-03-10 12:04 UTC, riverrun commented on lib/vutuv/accounts/user.ex
> +    field :email, :string
As email_addresses are a separate table, I don't think we need this entry.

2019-03-10 12:04 UTC, riverrun commented on priv/repo/migrations/20190307081841_create_users.exs
> +      add :email, :string
As email_addresses are a separate table, I don't think we need this entry - see comment for schema above.

2019-03-10 12:27 UTC, hendri-tobing commented on lib/vutuv/accounts.ex
> +  def get_email_address!(id), do: Repo.get!(EmailAddress, id)
Agree. The bang version function will cause crash the app if it does not work

2019-03-10 12:30 UTC, hendri-tobing commented on lib/vutuv/accounts/email_address.ex
> +    |> validate_length(:value, max: 80)
Ok. I will change the length to 255.

2019-03-10 12:34 UTC, hendri-tobing commented on lib/vutuv_web/views/user_view.ex
> +  alias VutuvWeb.UserView
Yes, we don’t need it now.

2019-03-10 12:35 UTC, hendri-tobing commented
Thank you for the review. I will fix them as soon as possible.

2019-03-11 15:32 UTC, wintermeyer reviewed
I'm not a big fan of the `some updates` title of this PR. ;-)

The emails which are send include "http://www.example.com" in development. Is there a possibility to make that http://localhost:4000 to make it a bit easier for new developers. It is not a show stopper but would be nice.

And the README needs an update of how the URL for production can be configured.

2019-03-12 01:33 UTC, hendri-tobing commented
> I'm not a big fan of the `some updates` title of this PR. ;-)
> 
> The emails which are send include "http://www.example.com" in development. Is there a possibility to make that http://localhost:4000 to make it a bit easier for new developers. It is not a show stopper but would be nice.
> 
> And the README needs an update of how the URL for production can be configured.

I will change the title and the email config for development

2019-03-12 05:29 UTC, riverrun approved these changes

2019-03-12 05:37 UTC, riverrun commented
@wintermeyer shall we merge this now? I'm happy with the changes. Once it is merged, I can rebase #584 and get that merged

2019-03-12 06:12 UTC, wintermeyer commented
@riverrun Go ahead with the merge.

2019-03-12 06:14 UTC, merged