Add email address context, routes, and bamboo for development
wintermeyer/vutuv pull request #597
Opened 2019-03-23 01:24 UTC by hendri-tobing

Add email address context so users able to submit many emails.

Update routes, related with email_addresses. 

Simple html.eex template for registration, sign in, add email.

Bamboo for development, so developer can view a sent email on localhost:4000/sent_email, then process the confirmation.

Some tests are still unresolved, seems they are related with user for testing. Please advise.

To do next: 
* user to verify additional emails
* sent email information once user has verified/confirmed 
* magic link?

2019-03-23 07:19 UTC, riverrun requested changes
Just a few minor comments.

About the comments about email confirmation, if you think the group needs to discuss it further, feel free to open an issue about that.

The travis build is failing, but if you make the changes I suggested to the forms, then it should pass.

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/templates/user/form.html.eex
> +<%= form_for @changeset, @action, fn f -> %>
This needs to be `form_for @changeset, @action, [], fn f`. Otherwise, dialyzer will complain (that's the error in the travis build).

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/templates/email_address/form.html.eex
> +<%= form_for @changeset, @action, fn f -> %>
This needs to be `form_for @changeset, @action, [], fn f`. Otherwise, dialyzer will complain (that's the error in the travis build).

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv/accounts.ex
> +  # def list_users, do: Repo.all(User)
Just remove these comments. If we want to know what was there before, we can just use git to tell us.

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv/accounts.ex
> +  # def get_user(id), do: Repo.get(User, id)
Remove comment

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv/accounts.ex
> +    # user = get_by(%{"user_id" => userid})
Remove comments

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv/accounts.ex
> +  @spec verify_email(User.t()) :: {:ok, EmailAddress.t()} | changeset_error
Could you tell me what this function is meant to be doing? I can't see what the purpose of it is.

Two more things: it needs documentation and only use `hd` if you are sure that the result will be a non-empty list.

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/controllers/authorize.ex
> +  def guest_check(%Plug.Conn{assigns: %{current_user: _current_user}} = conn, _opts) do
I don't think we need to change this. The `guest_check` plug is used to make sure that a user who is already logged in cannot access the login page.

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/controllers/confirm_controller.ex
>      case Confirm.verify(params) do
We need to think about when we are calling this function. I think it will be called one email at a time, so we will not need to process the list of email addresses in this function.

What do you think?

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/controllers/password_reset_controller.ex
> +    # email_addresses = Accounts.get_email_address(user.id)
Remove comment

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/controllers/email_address_controller.ex
> +  def create(conn, %{"email_address" => email_address_params}) do
We need to confirm each email that is created

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/controllers/password_reset_controller.ex
> +    for email_address <- email_addresses do
Do we want to send an email to all the addresses, or just the primary email?

2019-03-23 07:19 UTC, riverrun commented on priv/repo/migrations/20190312133648_create_users.exs
> +      # add :email, :string
Remove comment

2019-03-23 07:19 UTC, riverrun commented on priv/repo/migrations/20190312133648_create_users.exs
> +    # create unique_index(:users, [:email])
Remove comment

2019-03-23 07:19 UTC, riverrun commented on priv/repo/migrations/20190314153201_create_email_addresses.exs
> +    # create unique_index(:email_addresses, [:user_id])
Remove comment

2019-03-23 07:19 UTC, riverrun commented on test/vutuv/accounts/accounts_test.exs
> +      #
Remove comment

2019-03-23 07:19 UTC, riverrun commented on test/vutuv/accounts/accounts_test.exs
> +    # @valid_email_attrs %{
Remove comments

2019-03-23 07:19 UTC, riverrun commented on test/vutuv/accounts/accounts_test.exs
> +    #   @tag :skip
Remove comments. Please open an issue about needing to update the tests.

2019-03-23 07:19 UTC, riverrun commented on test/vutuv_web/controllers/session_controller_test.exs
> +      # conn = conn |> add_session(user) |> send_resp(:ok, "/")
Why is this commented out?

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/templates/page/index.html.eex
> +<section class="phx-hero">
Delete the templates/page directory. It is not needed.

2019-03-23 07:19 UTC, riverrun commented on lib/vutuv_web/views/page_view.ex
> +defmodule VutuvWeb.PageView do
Delete this file. It is not needed.

2019-03-23 22:35 UTC, hendri-tobing commented on lib/vutuv/accounts.ex
> +  @spec verify_email(User.t()) :: {:ok, EmailAddress.t()} | changeset_error
```suggestion
  @spec verify_email(User.t()) :: {:ok, EmailAddress.t()} | changeset_error
```

This is for updating the "verified" on the email table to "true". Right now, it is only used when user confirm/verify their email after registering (additional to "confirmed_at" on user table). Because email is a required field, so I use `hd`.

To make it efficient, I will remove this function and those lines to add confirm_user function.

2019-03-23 22:42 UTC, hendri-tobing commented on lib/vutuv_web/controllers/confirm_controller.ex
>      case Confirm.verify(params) do
Agree. The email that will be called is the email at position 1 or primary email.

2019-03-23 23:29 UTC, hendri-tobing commented on lib/vutuv_web/controllers/password_reset_controller.ex
> +    for email_address <- email_addresses do
Better to send it to all email addresses, to let user knows their password has been changed.

2019-03-24 03:29 UTC, hendri-tobing commented on test/vutuv_web/controllers/session_controller_test.exs
> +      # conn = conn |> add_session(user) |> send_resp(:ok, "/")
I will uncomment it, but this part `|> send_resp(:ok, "/")` seems need to be deleted. Otherwise, the left side is different from right side.
```
     left:  "/"
     right: "/users/10089"
```

2019-03-24 04:17 UTC, hendri-tobing commented on lib/vutuv_web/controllers/email_address_controller.ex
> +  def create(conn, %{"email_address" => email_address_params}) do
Noted. I will create a separated issue for this.

2019-03-25 09:49 UTC, riverrun requested changes
There's just one comment about the compile error that travis is warning about. Once you fix that, I will be happy to merge these changes.

2019-03-25 09:49 UTC, riverrun commented on lib/vutuv_web/controllers/authorize.ex
> -    |> redirect(to: Routes.user_path(conn, :show, user))
This is where there is an error with the travis build. You need to change it back to what it was - with the redirect to the user 'show' page.

2019-03-25 11:52 UTC, hendri-tobing commented on lib/vutuv_web/controllers/authorize.ex
> -    |> redirect(to: Routes.user_path(conn, :show, user))
> This is where there is an error with the travis build. You need to change it back to what it was - with the redirect to the user 'show' page.

This is done. Thank you.

2019-03-25 12:09 UTC, riverrun approved these changes

2019-03-25 12:09 UTC, merged