Update gravatar as a default avatar
wintermeyer/vutuv pull request #609
Opened 2019-04-13 14:33 UTC by hendri-tobing

When registering as a new user, it is automatically getting a default avatar from https://www.gravatar.com as described in #571 . If the new user does not have it on gravatar, the default avatar will be the vutuv logo.

2019-04-17 11:59 UTC, riverrun requested changes
Looks good - just a couple of small comments and a question.

2019-04-17 11:59 UTC, riverrun commented on lib/vutuv/accounts.ex
> +      case status do
This case can be simplified - for example:

```
case status do
  {_, 200, 'OK'} -> create_upload
  _ -> nil
end
```

2019-04-17 11:59 UTC, riverrun commented on lib/vutuv/accounts.ex
> +          _upload = %{
We don't need `_upload = ` here - just return the map.

2019-04-17 11:59 UTC, riverrun commented on lib/vutuv/accounts.ex
> +        img = get_gravatar(attrs["email"], new_user.id)
What happend when this function returns nil?

2019-04-18 06:24 UTC, hendri-tobing commented on lib/vutuv/accounts.ex
> +        img = get_gravatar(attrs["email"], new_user.id)
If the get_gravatar return nil, the avatar will be the default avatar of Vutuv (located at assets/static/images/avatars/)

2019-04-18 07:02 UTC, hendri-tobing commented
I have updated as advised. Please let me know if anything is missing. Thank you.

2019-04-18 23:14 UTC, riverrun approved these changes

2019-04-18 23:14 UTC, merged