Added tags in general context, install slug dependency
wintermeyer/vutuv pull request #624
Opened 2019-05-19 23:32 UTC by hendri-tobing

Added tags in general context, since tags will be used by many context like user_tag, post_tag, etc.  This PR also install a slug dependency.

2019-05-20 10:04 UTC, riverrun requested changes
Just one change requested.

Could you also give me a little more information, or an example, about how we would use tags?

2019-05-20 10:04 UTC, riverrun commented on lib/vutuv/generals.ex
> +    downcase_name =
Let's call `is_binary(attrs["name"])` just once - for example:

```
{downcase_name, slug_value} = if name = is_binary(attrs["name"]) do
  {String.downcase(name), Slugger.slugify_downcase(name)}
end
```

2019-05-20 22:21 UTC, hendri-tobing commented on lib/vutuv/generals.ex
> +    downcase_name =
This is done. Thank you.

2019-05-20 22:36 UTC, hendri-tobing commented
> Just one change requested.
> 
> Could you also give me a little more information, or an example, about how we would use tags?

Initially, I thought this schema name is "skills". As Stefan advised on #621, it should be renamed as "tags" because it can be more general and also can be used for other things, for example (belongs_to) user_tag or post_tag. 

For users, user_tag can be users' skills like "Elixir", "Erlang", etc. People can endorse those user_tag.

The schema of user_tag can be like this
```
belongs_to :user
belongs_to :tag
has_many :endorsements
```

2019-05-21 06:33 UTC, riverrun approved these changes

2019-05-21 06:33 UTC, merged